#ifndef SS_SOLAR_SYSTEM_CONSTANTS_H
#define SS_SOLAR_SYSTEM_CONSTANTS_H


#define EARTH_MASS			5.98E24			// kg
#define EARTH_RADIUS		6380000.0		// m
#define ASTRONOMIC_UNIT		149597892000.0	// m
#define SEC_PER_YEAR		31556926.0		// sec/yr

// Rayon des planetes (m)
#define SOLEIL_RAYON	109.0*EARTH_RADIUS
#define MERCURE_RAYON	0.387*EARTH_RADIUS
#define VENUS_RAYON		0.95*EARTH_RADIUS
#define TERRE_RAYON		1.0*EARTH_RADIUS
#define MARS_RAYON		0.53*EARTH_RADIUS
#define JUPITER_RAYON	11.2*EARTH_RADIUS
#define SATURNE_RAYON	9.3*EARTH_RADIUS
#define URANUS_RAYON	4.0*EARTH_RADIUS
#define NEPTUNE_RAYON 	3.9*EARTH_RADIUS
#define PLUTON_RAYON	0.18*EARTH_RADIUS

// Orbit radius	(demi grand-axe...) (m) 
#define MERCURE_ORBIT_A	0.387*ASTRONOMIC_UNIT
#define VENUS_ORBIT_A	0.723*ASTRONOMIC_UNIT
#define TERRE_ORBIT_A	1.0*ASTRONOMIC_UNIT
#define MARS_ORBIT_A	1.524*ASTRONOMIC_UNIT
#define JUPITER_ORBIT_A	5.203*ASTRONOMIC_UNIT
#define SATURNE_ORBIT_A	9.54*ASTRONOMIC_UNIT
#define URANUS_ORBIT_A	19.19*ASTRONOMIC_UNIT
#define NEPTUNE_ORBIT_A	30.06*ASTRONOMIC_UNIT
#define PLUTON_ORBIT_A	39.44*ASTRONOMIC_UNIT

// Orbit Excentricity
#define MERCURE_ORBIT_E	0.206
#define VENUS_ORBIT_E	0.007
#define TERRE_ORBIT_E	0.017
#define MARS_ORBIT_E	0.093
#define JUPITER_ORBIT_E	0.048
#define SATURNE_ORBIT_E	0.056
#define URANUS_ORBIT_E	0.046
#define NEPTUNE_ORBIT_E	0.010
#define PLUTON_ORBIT_E	0.248

// Periodes de revolution (s)
#define MERCURE_ORBIT_T	0.24*SEC_PER_YEAR
#define VENUS_ORBIT_T	0.615*SEC_PER_YEAR
#define TERRE_ORBIT_T	1*SEC_PER_YEAR
#define MARS_ORBIT_T	1.88*SEC_PER_YEAR
#define JUPITER_ORBIT_T	11.86*SEC_PER_YEAR
#define SATURNE_ORBIT_T	29.46*SEC_PER_YEAR
#define URANUS_ORBIT_T	84.04*SEC_PER_YEAR
#define NEPTUNE_ORBIT_T	164.8*SEC_PER_YEAR
#define PLUTON_ORBIT_T	247.7*SEC_PER_YEAR

// Masses relatives a la Terre
#define	SOLEIL_RELATIVE_MASS	330000.0
#define MERCURE_RELATIVE_MASS	0.056
#define VENUS_RELATIVE_MASS		0.82
#define TERRE_RELATIVE_MASS		1
#define MARS_RELATIVE_MASS		0.11
#define JUPITER_RELATIVE_MASS	318
#define SATURN_RELATIVE_MASS	95
#define URANUS_RELATIVE_MASS	15
#define NEPTUNE_RELATIVE_MASS	17
#define PLUTON_RELATIVE_MASS	0.002


#endif 